# -*- coding: utf-8 -*-
"""sprint.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zFo99bhMKZFAwmlfdAaXbo_LbexRlz-6
"""

import pandas as pd
import numpy as np

df= pd.read_csv('MOCK_DATA.csv')

df

Lo = df.sort_values(by= 'Estatura', ascending=True) #Lo = Esta es la lista ascendente de estatura

Lo

Ld = df.sort_values(by= 'Estatura', ascending=False) #Ld = Esta es la lista descendente de estatura

No = df.sort_values(by= 'Nombre', ascending=True) #No = Esta es la lista de nombres ordenados alfabéticamente

Lvi = df.sort_values(by= ['Nombre','Estatura'], ascending=True) #Lvi = Esta es la lista ordenada de manera ascendente de varios items











